// <auto-generated />
using System;
using ASSIGMENT_Danh_Ba.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASSIGMENT_Danh_Ba.Migrations
{
    [DbContext(typeof(DB_CONTEXT_DanhBa))]
    [Migration("20210731165619_Nguoi")]
    partial class Nguoi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASSIGMENT_Danh_Ba.Models.DanhBa", b =>
                {
                    b.Property<Guid>("IdDanhBa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdNguoi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SDT2")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdDanhBa");

                    b.HasIndex("IdNguoi");

                    b.ToTable("DANHBA");
                });

            modelBuilder.Entity("ASSIGMENT_Danh_Ba.Models.Nguoi", b =>
                {
                    b.Property<Guid>("IdNguoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NamSinh")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdNguoi");

                    b.ToTable("Nguoi");
                });

            modelBuilder.Entity("ASSIGMENT_Danh_Ba.Models.DanhBa", b =>
                {
                    b.HasOne("ASSIGMENT_Danh_Ba.Models.Nguoi", "Nguois")
                        .WithMany("DanhBas")
                        .HasForeignKey("IdNguoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nguois");
                });

            modelBuilder.Entity("ASSIGMENT_Danh_Ba.Models.Nguoi", b =>
                {
                    b.Navigation("DanhBas");
                });
#pragma warning restore 612, 618
        }
    }
}
